config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'

  get 'reviews/create'

  get 'reviews/edit'

  get 'reviews/update'

  get 'reviews/destroy'

 root to: 'pages#home'
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
 resources :villas do
   resources :bookings, only: [:new, :create]
 end

 resources :bookings do
  resources :reviews, only: [:new, :create, :edit, :update, :destroy]
end
 post 'bookings/:id/approve', to: 'bookings#approve', as: :approve
 post 'bookings/:id/reject', to: 'bookings#reject', as: :reject
 resources :users, only: [:edit, :update, :show]
 mount Attachinary::Engine => "/attachinary"
end

app/models/villa.rb
class Villa < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, :through => :bookings
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  # has_attachment :photo
  has_attachments :images, maximum: 30
  # validates :images, presence: true
  validates :name, presence: true
  validates :address, presence: true
  validates :price, presence: true
end

app/controllers/villas_controller.rb
class VillasController < ApplicationController
skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    # Need to handle the case where only one of the two inputs is filled
    if params[:villa][:start_date] == "" || params[:villa][:end_date] == ""
      @villa = Villa.all
      @villas = Villa.where.not(latitude: nil, longitude: nil)

      @hash = Gmaps4rails.build_markers(@villas) do |villa, marker|
        marker.lat villa.latitude
        marker.lng villa.longitude
        marker.infowindow render_to_string(partial: "/villas/map_box", locals: { villa: villa })
      end
    else
      @start_date_search = Date.parse(params[:villa][:start_date])
      @end_date_search = Date.parse(params[:villa][:end_date])
      # Loop through all villas
      @villa = []
      @allvillas = Villa.all
      @allvillas.each do |villa|
        @counter = 0
        @villabookings = villa.bookings.where(status: ["Approved", "Pending", "pending"])
        @villabookings.each do |booking|
          if (booking.end_date < @start_date_search && booking.end_date < @end_date_search\
          && booking.start_date < @start_date_search && booking.start_date < @end_date_search )\
          || (booking.end_date > @start_date_search && booking.end_date > @end_date_search\
          && booking.start_date > @start_date_search && booking.start_date > @end_date_search )
            @counter += 1
          end
        end
        @villa << villa if (@counter == @villabookings.length || @villabookings.nil?)
      end
      # Need to handle case where no villa is available at the dates
    end

    @villas_to_display_on_map_not_filtered = Villa.where.not(latitude: nil, longitude: nil)
    @villas_to_display_on_map_filtered = []
    @villas_to_display_on_map_not_filtered.each do |villa|
      @villas_to_display_on_map_filtered << villa if @villa.include?(villa)
    end
    @hash = Gmaps4rails.build_markers(@villas_to_display_on_map_filtered) do |villa, marker|
      marker.lat villa.latitude
      marker.lng villa.longitude
      marker.infowindow render_to_string(partial: "/villas/map_box", locals: { villa: villa })
    end
    # Need to handle case where no villa is available at the dates

  end


  def show
    @start_date_search = params[:villa][:start_date]
    @end_date_search = params[:villa][:end_date]
    @villa = Villa.find(params[:id])
    @booking = Booking.new
    @reviews = @villa.reviews
    @hash = Gmaps4rails.build_markers([@villa]) do |villa, marker|
      marker.lat villa.latitude
      marker.lng villa.longitude
      marker.infowindow render_to_string(partial: "/villas/map_box", locals: { villa: villa })
    end
  end

  def new
    @villa = Villa.new
  end

  def create
    # need to put an if if all the validations don't go through
    @villa = Villa.new(villa_params)
    @villa.user = current_user
    if @villa.save
      redirect_to villa_path(@villa)
    else
      render 'new'
    end
  end

  def edit
    @villa = Villa.find(params[:id])
    @user = @villa.user_id
  end

  def update
    @villa = Villa.find(params[:id])
    @villa.update(villa_params)
    redirect_to villa_path(@villa)
  end

  def destroy
    @villa = Villa.find(params[:id])
    @villa.destroy
    redirect_to villas_path
  end

  private

  def villa_params
    params.require(:villa).permit(:name, :address, :price, :number_of_guests, :number_of_beds, :category, :pool, :heated_pool,
    :number_of_bathrooms, :number_of_rooms, :arrival_time, :jacuzzi, :parking, :wifi, :smoking_allowed, :description, :photo, images: [])
  end
end

app/helpers/villas_helper.rb
module VillasHelper
end

app/views/villas/_carroussel.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">


    <% @villa.images.each do |image| %>
      <% if @villa.images.index(image) == 0 %>
        <div class="item active">
          <%= cl_image_tag image.path, crop: :fill %>
        </div>
      <% else %>
        <div class="item">
          <%= cl_image_tag image.path, crop: :fill %>
        </div>
      <% end %>
    <% end %>



  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/villas/_form.html.erb
<%= simple_form_for [@villa] do |f| %>
  <%= f.error_notification %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :price, input_html: { min: 0, step: "any"}%>
  <%= f.input :category %>
  <%= f.input :number_of_guests %>
  <%= f.input :number_of_rooms %>
  <%= f.input :number_of_bathrooms %>
  <%= f.input :number_of_beds %>
  <%= f.input :pool %>
  <%= f.input :jacuzzi %>
  <%= f.input :heated_pool %>
  <%= f.input :wifi %>
  <%= f.input :parking %>
  <%= f.input :smoking_allowed %>
  <%= f.input :images, as: :attachinary %>

  <%= f.submit "Submit", class: "form-btn btn btn-primary" %>
<% end %>

app/views/villas/_map_box.html.erb
<div class="infowindow">
  <div class="card-wrapper">
    <%= link_to villa_path(villa) do %>

      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
         url('<%= cl_image_path villa.images.first.path, crop: :fill %>')">
        <div class="card-hover">check it out!</div>
      </div>


      <div class="card-description">
        <div class="villa-name"><%= villa.name %></div>
        <div class="villa-location"><%= villa.address %></div>
        <div class="villa-price"><%= villa.price.to_i %>€</div>
      </div>

    <% end %>
  </div>


</div>

app/views/villas/edit.html.erb
<div class="bg-light-background padded form-wrapper">
  <div class="col-xs-6 col-xs-offset-3">
    <div class="form-container">
      <h2>Edit my villa</h2>
      <%= render 'form' %>
      <br>
       <%= link_to "Back", user_path(@user)%>
    </div>
  </div>
</div>

app/views/villas/index.html.erb
<%= link_to "Add a villa", new_villa_path %>

<div class="container">
  <div class="row" id="index-form">
    <div class="col-xs-12">
      <div class="form-container">
        <%= simple_form_for :villa, :url => url_for(:action => 'index', :controller => 'villas'), :method => 'get' do |f| %>
          <%= f.input :start_date, as: :string, input_html:{class: "datepicker bg-transparent", value: @start_date_search }, label: false %>
          <%= f.input :end_date, as: :string, input_html:{class: "datepicker bg-transparent",  value: @end_date_search }, label: false %>
          <%= f.submit 'UPDATE', class: "btn btn-medium padded" %>
          <% end %>
          <!-- second hidden form -->
          <%= simple_form_for :villa do |f| %>
          <%= f.input :start_date, as: :hidden, input_html:{class: "datepicker bg-transparent", value: @start_date_search }, label: false %>
          <%= f.input :end_date, as: :hidden, input_html:{class: "datepicker bg-transparent",  value: @end_date_search }, label: false %>
          <% end %>
        </div>
      </div>
    </div>
  <div class="row">
    <div class="col-xs-12 col-md-6">
      <div class="row">
        <div class="search-area">
          <% @villa.each do |villa| %>
            <div class="col-xs-12">
              <div class="card-wrapper">
                <%= link_to villa_path(villa) do %>

                <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
                   url('<%= cl_image_path villa.images.first.path, height: 300, width: 400, crop: :fill %>')">
                <div class="card-hover">check it out!</div>

                <div class="card-description">
                  <div class="villa-name"><%= villa.name %></div>
                  <div class="villa-location"><%= villa.address %></div>
                  <div class="villa-price"><%= villa.price.to_i %>€</div>
                </div>
                </div>

                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-xs-12 col-md-6">
      <div id="index-map" style="height: calc(100vh - 90px);"></div>
    </div>
  </div>
</div>


<% content_for(:after_js) do %>
  <script>
    $(document).ready(function() {
      var styles = [{featureType:"administrative",elementType:"labels.text.fill",stylers:[{color:"#444444"}]},{featureType:"landscape",elementType:"all",stylers:[{color:"#f2f2f2"}]},{featureType:"poi",elementType:"all",stylers:[{visibility:"off"}]},{featureType:"road",elementType:"all",stylers:[{saturation:-100},{lightness:45}]},{featureType:"road.highway",elementType:"all",stylers:[{visibility:"simplified"}]},{featureType:"road.arterial",elementType:"labels.icon",stylers:[{visibility:"off"}]},{featureType:"transit",elementType:"all",stylers:[{visibility:"off"}]},{featureType:"water",elementType:"all",stylers:[{color:"#c2a267"},{visibility:"on"}]}];
      var handler = Gmaps.build('Google');
      handler.buildMap({
        provider: {
          styles: styles
        },
        internal: { id: 'index-map' } }, function() {
        markers = handler.addMarkers(<%= raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
        if (markers.length == 0) {
          handler.getMap().setZoom(2);
        } else if (markers.length == 1) {
          handler.getMap().setZoom(14);
        }
      });
    });
  </script>
<% end %>

app/views/villas/new.html.erb
<div class="bg-light-background padded form-wrapper">
  <div class="col-xs-6 col-xs-offset-3">
    <div class="form-container">
      <h1>Become a host</h1>
      <p>List your villa</p>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/villas/show.html.erb
<%= render 'carroussel' %>

<div id="container">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-md-8" id="description">
        <!-- summary = user image villa and overview icons -->
        <div class="show-padding separator" id="summary">
          <div id="user-image">
            <% user_url =  @villa.user.facebook_picture_url || "http://placehold.it/70x70" %>
            <%= image_tag user_url, {class: "img-circle"} %>
          </div>

          <div id="villa-overview">
            <h2><%= @villa.name %></h2>
            <p><%= @villa.address %></p>
              <div class="villa-icon-container">
                <div class="villa-icon-card">
                  <%= image_tag "villa.svg", class: "villa-icon" %>
                  <%= @villa.category %> Villa
                </div>
                <div class="villa-icon-card">
                  <%= image_tag "guests.png", class: "villa-icon" %>
                  <%= @villa.number_of_guests %> Guests
                </div>
                <div class="villa-icon-card">
                  <%= image_tag "room.svg", class: "villa-icon" %>
                  <%= @villa.number_of_rooms %> Rooms
                </div>
                <div class="villa-icon-card">
                  <%= image_tag "bed.svg", class: "villa-icon" %>
                  <%= @villa.number_of_beds %> Beds
                </div>
              </div>
            </div>
          </div>
    <!-- end of summary -->

      <!-- spacing -->
      <br><br><br>
      <!-- spacing -->

      <div class="show-padding separator text-justify">
        <strong><p>About this villa</p></strong><br>
        <!-- Replace with user description -->
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda necessitatibus, nemo asperiores non quibusdam laudantium accusantium iure cum consectetur nobis a et mollitia accusamus rerum, eius minima quaerat praesentium quia.</p>
      </div>

      <!-- Villa characteristics -->
      <div class="villa-features-container show-padding separator">
        <div class="show-card">
          <div>
            The space
          </div>
        </div>
        <div class="show-card text-align">
          <div>
            Accomodates: <strong><%= @villa.number_of_guests %></strong>
          </div>
          <div>
            Bathrooms: <strong><%= @villa.number_of_bathrooms %></strong>
          </div>
          <div>
            Rooms: <strong><%= @villa.number_of_rooms %></strong>
          </div>
        </div>
        <div class="show-card">
          <div>
            Beds: <strong><%= @villa.number_of_beds %></strong>
          </div>
          <div>
            Property type: <strong><%= @villa.category %></strong>
          </div>
        </div>
      </div>
      <div class="villa-features-container show-padding separator">
        <div class="show-card">
          <div>
            Amenities
          </div>
        </div>
        <div class="show-card">
          <div>
            <% if @villa.pool %>
              <strong> Pool </strong>
            <% else %>
              <div class="line-through">Pool</div>
            <% end %>
          </div>
          <div>
            <% if @villa.heated_pool %>
              <strong> Heated pool </strong>
            <% else %>
              <div class="line-through">Heated pool</div>
            <% end %>
          </div>
          <div>
            <% if @villa.jacuzzi %>
              <strong> Jacuzzi </strong>
            <% else %>
              <div class="line-through">Jacuzzi</div>
            <% end %>
          </div>
          <div>
            <% if @villa.parking %>
              <strong> Parking </strong>
            <% else %>
              <div class="line-through">Parking</div>
            <% end %>
          </div>
        </div>
        <div class="show-card">
          <div>
            <% if @villa.wifi %>
              <strong> Wifi </strong>
            <% else %>
              <div class="line-through">Wifi</div>
            <% end %>
          </div>
          <div>
            <% if @villa.smoking_allowed %>
              <strong> Smoking allowed </strong>
            <% else %>
              <div class="line-through">Smoking allowed</div>
            <% end %>
          </div>
        </div>
      </div>
      <!-- Villa characteristics -->
      <div class="show-padding" id="show-back-link">
          <%= link_to "Back", villas_path %>
      </div>

      <!-- reviews -->

        <div class="row">
          <div class="col-xs-12 ">
            <%@reviews.each do |review| %>
              <div class="review-card">
                <div class="review-avatar">
                  <%= user_picture_avatar(review.user, "avatar-review-bordered") %>
                </div>
                <div class="content">
                  <div class="review-name">
                    <strong><%= review.user.first_name  %></strong>, <%=review.created_at.strftime("on %m/%d/%Y")  %>
                  </div>
                  <div class="review-stars">
                    <%review.rating.to_i.times { %>
                      <i class="fa fa-star" aria-hidden="true"></i>
                    <% } %>
                  </div>
                  <div class="review-content">
                    <%=  review.content %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>


      <!-- end of reviews -->

      <!-- Map -->
      <div id="index-map" style="height: 600px;"></div>

      <% content_for(:after_js) do %>
        <script>
          $(document).ready(function() {
            var styles = [{featureType:"administrative",elementType:"labels.text.fill",stylers:[{color:"#444444"}]},{featureType:"landscape",elementType:"all",stylers:[{color:"#f2f2f2"}]},{featureType:"poi",elementType:"all",stylers:[{visibility:"off"}]},{featureType:"road",elementType:"all",stylers:[{saturation:-100},{lightness:45}]},{featureType:"road.highway",elementType:"all",stylers:[{visibility:"simplified"}]},{featureType:"road.arterial",elementType:"labels.icon",stylers:[{visibility:"off"}]},{featureType:"transit",elementType:"all",stylers:[{visibility:"off"}]},{featureType:"water",elementType:"all",stylers:[{color:"#c2a267"},{visibility:"on"}]}];
            var handler = Gmaps.build('Google');
            handler.buildMap({
              provider: {
                styles: styles
              },
              internal: { id: 'index-map' } }, function() {
              markers = handler.addMarkers(<%= raw @hash.to_json %>);
              handler.bounds.extendWith(markers);
              handler.fitMapToBounds();
              if (markers.length == 0) {
                handler.getMap().setZoom(2);
              } else if (markers.length == 1) {
                handler.getMap().setZoom(14);
              }
            });
          });
        </script>
      <% end %>



    </div>
    <!-- end of villa column -->
    <!-- spacing -->
    <br><br><br>
    <!-- spacing -->

    <!-- start of booking form -->
    <div class="col-xs-12 col-md-4" id="booking-info-container">
      <div id="booking-info">
          <%= simple_form_for [@villa, @booking] do |f| %>
            <%= f.error_notification %>
            <%= f.input :start_date, as: :string, input_html:{class: "datepicker", value: @start_date_search} %>
            <%= f.input :end_date, as: :string, input_html:{class: "datepicker", value: @end_date_search} %>
            <%= f.input :number_of_guests, input_html: { min: 0, step: "1", :value => "2" } %>

            <%= f.submit "Book", class: "btn btn-primary" %>
          <% end %>
      </div>
    </div>
    <!-- end of booking form -->