config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'

  get 'reviews/create'

  get 'reviews/edit'

  get 'reviews/update'

  get 'reviews/destroy'

 root to: 'pages#home'
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
 resources :villas do
   resources :bookings, only: [:new, :create]
 end

 resources :bookings do
  resources :reviews, only: [:new, :create, :edit, :update, :destroy]
end
 post 'bookings/:id/approve', to: 'bookings#approve', as: :approve
 post 'bookings/:id/reject', to: 'bookings#reject', as: :reject
 resources :users, only: [:edit, :update, :show]
 mount Attachinary::Engine => "/attachinary"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, omniauth_providers: [:facebook]
   has_many :villas
   has_many :bookings
   has_attachment :photo

  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @villas = Villa.where(user_id: @user.id)
    villas_id = []
    @villas.each do |villa|
      villas_id << villa.id
    end
    @bookings = Booking.where(user_id: @user.id)
    @bookings_as_a_host = Booking.where(villa_id: villas_id)
    @bookings_as_a_host_pending = Booking.where(villa_id: villas_id, status: 'pending')
    # I take bookings where villa_id belongs to all the ids from @villas (which are my villas)
  end

  #to-do: Protect the edit with authentification
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :photo, :date_of_birth)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  #use method everytime you want to add a user picture
  # simply write the following in your show
  # <%= user_picture_avatar(the user you want to display, "the class you want to give the picture" %>
  # example: <%= user_picture_avatar(current.user, "avatar-large")
  def user_picture_avatar(user, image_class)
   if user.photo?
    cl_image_tag(user.photo.path, { class: image_class})
   else
    avatar_url = user.facebook_picture_url || "http://placehold.it/100x100"
    image_tag avatar_url, class: image_class
   end
  end
end

app/views/users/_form.html.erb
<%= simple_form_for [@user] do |f| %>
  <%= f.error_notification %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :date_of_birth, as: :string, input_html: {type: :date}%>
  <%= f.input :photo, as: :attachinary %>

  <%= f.submit "Submit", class: "form-btn btn btn-primary" %>
<% end %>

app/views/users/_review-dropdown.htmp.erb
_review-dropdown.htmp.erb

app/views/users/show.html.erb
<div class="wrapper bg-light-background padded" id="user-show">
  <div class="container bg-white">
    <div class="showcontainer">
      <div class="profile">
        <%= link_to edit_user_path(current_user) do %>
        <div id ="profile-info">
          <h2> Profile Info </h2>
          <br>
          <%= user_picture_avatar(@user, "profilep")  %>
          <p>
          <ul>
            <li><%= @user.first_name %> <%= @user.last_name %> </li>
            <li><%= @user.email %></li>
            <li> User since <%= @user.created_at.year %></li>
          </ul>
           <%= link_to "Edit Info", edit_user_path(current_user), class: "navbar-wagon-link" %>
          </p>
        </div>
        <% end %>
      </div>
      <div class="listings">
        <h2> My Listings </h2>
        <% if @villas.empty? %>
          <div class="request_notif">no listings at the moment</div>
        <% else %>
          <% @villas.each do |villa| %>
        <div class="row">
          <div class="col-xs-12 padded">
            <%= link_to villa_path(villa) do %>
            <div class="listings-card-wrapper">
              <div class="listings-card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
                 url('<%= cl_image_path villa.images.first.path, height: 100, width: 200, crop: :fill %>')">
              </div>
              <div class="listings-card-description">
                <div class="villa-name"><strong><%= villa.name %></strong></div>
                <div class="villa-location"><%= villa.address %></div>
                <div class="villa-price"><%= villa.price.to_i %>€</div>
                <div class="villa-links"><%= link_to "Edit", edit_villa_path(villa) %>|<%= link_to "Delete", villa_path(villa), method: :delete, data: {confirm: "Are you sure to delete this villa permanently"} %></div>
              </div>
            </div>
            <% end %>
          </div>
          <% end %>
          <% end %>
          <div class="bottom-button">
          <%= link_to "Add Listing", new_villa_path, class: "navbar-wagon-button btn"%>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container bg-white text-center">
    <div class="col-xs-12">
      <div class="bookings">
        <h2> My Bookings </h2>
        <div class="row">
          <div class="col-xs-12 padded">
            <% @bookings.each do |booking| %>
              <% @villa = Villa.find(booking.villa_id) %>
              <%= link_to villa_path(@villa) do %>
                <div class="listings-card-wrapper margini">
                  <div class="listings-card"><%= cl_image_tag @villa.images.first.path, height: 100, width: 200, crop: :fill %></div>

                  <div class="bookings-card-description">
                    <div class="villa-name"><strong><%= link_to @villa.name, villa_path(@villa) %></strong></div>
                    <div class="villa-location"><%= link_to @villa.address, villa_path(@villa) %></div>
                    <div class="booking-dates">[<%= booking.start_date%> - <%= booking.end_date%>]</div>
                    <div class="review-link"> <%= link_to "review",  new_booking_review_path(booking.id) %></div>
                  </div>
                  <div class="bookings-status-card">
                    <% if booking.status == "Pending" %>
                      <%= image_tag "pending.svg", class: "status"%>
                    <% elsif booking.status == "Rejected" %>
                      <%= image_tag "rejected.svg", class: "status"%>
                    <% else %>
                      <%= image_tag "approved.svg", class: "status" %>
                    <% end %>
                  </div>
                </div>
            <% end %>
          <% end %>
        </div>
      </div>
      <div  class ="bottom-button">
      <%= link_to "Book Another", root_path, class: "navbar-wagon-button btn"%>
      </div>
      </div>
    </div>
  </div>
  <div class="container bg-white text-center">
    <div class="host-bookings">
      <h2> My Bookings as a host </h2>
      <div class="row">
        <div class="col-xs-12">
        <% if @notifs == 0 %>
          <div class="request_notif">0 pending requests at the moment</div>
        <% else %>
          <div class="col-xs-12">
          <% @bookings_as_a_host.each do |booking| %>
            <div class="host-pending-wrapper">
              <% @villa = Villa.find(booking.villa_id) %>
              <% @user = User.find(booking.user_id) %>
              <div class="user-card">
                <%= user_picture_avatar(@user, "user-avatar")  %>
              </div>
              <div class="pending-card-description">
                <div class="user-name"><%= @user.first_name %> <%= @user.last_name %></div>
                <div class="user-dob"> Born <%= @user.date_of_birth %></div>
                <div class="villa-name"><strong><%= link_to @villa.name, villa_path(@villa) %></strong></div>
                <div class="booking-guests">Guests: <%= booking.number_of_guests%></div>
                <div class="booking-dates">[<%= booking.start_date%> - <%= booking.end_date%>]</div>
              </div>
              <div class="host-actions">
                <%= link_to "Approve", approve_path(booking), class: "btn btn-success btn-action", method: :post, data: {confirm: "Are you sure you want to approve this booking?"} %>
                <%= link_to "Reject", reject_path(booking), class: "btn btn-danger btn-action", method: :post, data: {confirm: "Are you sure you want to reject this booking?"} %>
              </div>
            </div>
          <% end %>
          </div>
        <% end %>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 ">
          <div class="host-card">
          <% @bookings_as_a_host.each do |booking| %>
            <div class="col-xs-12">
              <div class="host-pending-wrapper">
                <% @villa = Villa.find(booking.villa_id) %>
                <% @user = User.find(booking.user_id) %>
                <div class="villa-card">
                  <div class="listings-card" style="background-image:
                   url('http://pinandpin.com/wp-content/uploads/2013/11/395_2CL_2175_VILLA_IVY_x-1200x798.jpg')">
                  </div>
                </div>
                <div class="pending-card-description">
                  <div class="user-name"><%= @user.first_name %> <%= @user.last_name %></div>
                  <div class="user-dob"> Born <%= @user.date_of_birth %></div>
                  <div class="villa-name"><strong><%= link_to @villa.name, villa_path(@villa) %></strong></div>
                  <div class="booking-guests">Guests: <%= booking.number_of_guests%></div>
                  <div class="booking-dates">[<%= booking.start_date%> - <%= booking.end_date%>]</div>
                </div>
                <div class="bookings-status-card">
                  <% if booking.status == "Approved" %>
                    <%= image_tag "approved.svg", class: "status"%>
                  <% elsif booking.status == "Rejected" %>
                    <%= image_tag "rejected.svg", class: "status"%>
                  <% else %>
                    <%= image_tag "pending.svg", class: "status" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row" >
      <%= link_to "Back", villas_path %>
    </div>
  </div>
</div>

app/views/users/update.html.erb
<div class="form-wrapper bg-light-background padded">
  <div class="col-xs-6 col-xs-offset-3">
    <div class="form-container">
      <h1>Your Profile Info</h1>
      <p>Please check if everything is correct</p>
        <div class="form">
          <%= render 'form' %>
        </div>
       <br>
       <%= link_to "Back", user_path(@user)%>
    </div>
  </div>
</div>